### ISSUE TITLE
volume xxx is used in service "symfony" but no declaration was found in the volumes section.

### ISSUE THREAD

**Issue by grekpg** [bourdeau/docker-symfony4#1]
i get error
`ERROR: Named volume "home/grek/PhpstormProjects/mea.crm4:/var/www/app:rw" is used in service "symfony" but no declaration was found in the volumes section.`

.evn

```
SYMFONY_PATH=home/grek/PhpstormProjects/mea.crm4
DB_ROOT_PASS=bralion
SYMFONY_DB_NAME=bralion
SYMFONY_DB_USER=root
SYMFONY_DB_PATH=123
```

docker-compose.yml

    version: "2"
    
    services:
    
       symfony:
         build: php-7.2 # You can also use ubuntu-17.10
         container_name: itbcode_bralion_symfony
         ports:
           - "8080:80"
         expose:
             - "80"
         restart: always
         volumes:
             - ${SYMFONY_PATH}:/var/www/app
         # https://stackoverflow.com/questions/37100358/docker-composer-exited-with-code-0
         tty: true
         depends_on:
             - db
    
       db:
         image: mysql:5.7
         container_name: itbcode_bralion_mysql
         volumes:
           - db_data:/var/lib/mysql
         restart: always
         environment:
           MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
           MYSQL_DATABASE: ${SYMFONY_DB_NAME}
           MYSQL_USER: ${SYMFONY_DB_USER}
           MYSQL_PASSWORD: ${SYMFONY_DB_PATH}
         ports:
             - "3307:3306"
         expose:
             - "3306"
    
    volumes:
        db_data:

php-7.2/app.conf

    <VirtualHost *:80>
        ServerName localhost
        DocumentRoot /var/www/app/public
        <Directory /var/www/app/public>
            Options -Indexes
            AllowOverride All
            Require all granted
        </Directory>
    </VirtualHost>

php-7.2/app.conf

    <VirtualHost *:80>
        ServerName localhost
        DocumentRoot /var/www/app/public
        <Directory /var/www/app/public>
            Options -Indexes
            AllowOverride All
            Require all granted
        </Directory>
    </VirtualHost>

php-7.2/Dockerfile

    FROM php:7.2.1-apache
    
    MAINTAINER Pierre-Henri Bourdeau
    
    # Debian dep
    RUN apt-get update
    RUN apt-get install -y vim
    
    # Install php extensions
    RUN docker-php-ext-install pdo pdo_mysql
    
    # Install Composer
    RUN curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer && chmod +x /usr/local/bin/composer
    
    # Bashrc
    RUN rm /root/.bashrc
    ADD .bashrc /root/.bashrc
    
    # Cleaning
    RUN rm -rf /etc/apache2/sites-available/* && rm -rf /etc/apache2/sites-enabled/*
    RUN rm -rf /var/www/*
    
    # Conf Apache2
    RUN mkdir /var/www/app
    RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf
    ADD app.conf /etc/apache2/sites-available/app.conf
    RUN usermod -u 1000 www-data
    RUN a2ensite app.conf
    RUN service apache2 restart
    
    WORKDIR /var/www/app
    
    
    EXPOSE 80

**Comment by gdk21** [comment]
Did you find an issue? thx

**Comment by grekpg** [comment]
yes but it was long time ago and i dont remember solution...
